SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM SALGRADE;

SHOW USER

-- 계층형 조회 실습
SELECT MAX(LEVEL)
FROM EMP
START WITH MGR IS NULL
CONNECT BY PRIOR EMPNO=MGR;

-- 1
SELECT LEVEL, ENAME, EMPNO, MGR
FROM EMP
START WITH UPPER(JOB)='PRESIDENT'
CONNECT BY PRIOR EMPNO=MGR;

--2
SELECT LEVEL, ENAME, EMPNO, MGR, CONNECT_BY_ISLEAF
FROM EMP
START WITH ENAME='JONES'
CONNECT BY PRIOR MGR=EMPNO;

-- ROWID 조회하기
SELECT ROWID, ENAME 
FROM EMP;

-- ROWID 중복 제거에 활용
-- EMP 테이블에서 DEPTNO 별로 한 명의 DEPTNO 와 ENAME 조회
SELECT ENAME, DEPTNO 
FROM EMP
WHERE ROWID IN (SELECT MAX(ROWID) FROM EMP GROUP BY DEPTNO);


-- ROWNUM 조회하기
SELECT ROWNUM, ENAME 
FROM EMP
WHERE DEPTNO=10;

-- FETCH OFFSET 예시
-- 급여 내림차순 정렬하여 5개 데이터 조회
SELECT *
FROM EMP
ORDER BY SAL DESC
OFFSET 0
ROWS FETCH NEXT 5 ROWS ONLY;

-- SYNONYM 예시

CREATE SYNONYM 사원 FOR EMP;

SELECT * FROM 사원;
DROP SEQUENCE SEQDATA1

-- SEQUENCE 예시
-- SEQUENCE 생성
CREATE SEQUENCE SEQDATA1
	START WITH 50
	INCREMENT BY 3;

-- SEQUENCE 값 확인
SELECT SEQDATA1.NEXTVAL
FROM DUAL;

-- 시퀀스 이용한 데이터 삽입
INSERT INTO DEPT(DEPTNO,DNAME,LOC) VALUES(SEQDATA1.NEXTVAL,'개발','판교');

-- EMP 테이블에서 JOB별로 SAL의 평균/합계를 조회
SELECT NVL(JOB,'TOTAL'), AVG(SAL) 급여평균
FROM EMP
GROUP BY ROLLUP(JOB);

-- DEPTNO별로 SAL의 합계를 조회
-- 숫자 컬럼은 조회 시 DECODE 함수 이용해야 함
-- DECODE 값이 NULL이면 전체, 아니면 DEPTNO 변환하여 조회
SELECT DECODE(DEPTNO,NULL,'TOTAL',DEPTNO), SUM(SAL) 급여합계
FROM EMP
GROUP BY ROLLUP(DEPTNO);

-- 
SELECT DEPTNO,JOB, SUM(SAL) 급여합계
FROM EMP
GROUP BY ROLLUP(DEPTNO,JOB)
ORDER BY DEPTNO;

-- 
SELECT DEPTNO,NVL(JOB,'TOTAL'), SUM(SAL) 급여합계
FROM EMP
GROUP BY DEPTNO,ROLLUP(JOB);

-- CUBE 예시
SELECT DEPTNO,JOB, SUM(SAL) 급여합계
FROM EMP
GROUP BY CUBE(DEPTNO,JOB)
ORDER BY DEPTNO;

-- grouping 함수
SELECT DEPTNO,GROUPING(DEPTNO),JOB,GROUPING(JOB), SUM(SAL) 급여합계
FROM EMP
GROUP BY ROLLUP(DEPTNO,JOB)
ORDER BY DEPTNO;

-- grouping 함수 이용하여 합계 타이틀 생성
SELECT DEPTNO,DECODE(GROUPING(DEPTNO),1,'전체합계'),JOB,DECODE(GROUPING(JOB),1,'부서 합계'), SUM(SAL) 급여합계
FROM EMP
GROUP BY ROLLUP(DEPTNO,JOB)
ORDER BY DEPTNO;

-- GROUPING SETS 사용 시 컬럼 별 집계 
SELECT DEPTNO,JOB, SUM(SAL) 급여합계
FROM EMP
GROUP BY GROUPING SETS(DEPTNO,JOB)

-- WINDOW 함수 예제 -에러
SELECT ENAME, SAL, SAL/SUM(SAL)
FROM EMP;

-- WINDOW 함수 예제
-- SUM(SAL) 전부 복사하여 cardinality 맞춰줌
SELECT ENAME, SAL, SAL*100/SUM(SAL) OVER() AS "급여 비율"
FROM EMP;

-- EMP 테이블에서 EMPNO, ENAME, SAL, 현재행까지 SAL 합계 조회
SELECT EMPNO, ENAME, SAL, SUM(SAL) OVER(
ORDER BY SAL ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) "TOTAL"
FROM EMP;

-- 부서별 급여 평균 PARTITION 이용
SELECT EMPNO, ENAME, SAL, ROUND(AVG(SAL) OVER(PARTITION BY DEPTNO)) "부서별 평균 급여"
FROM EMP;

-- 부서별 SAL 순위 부여
SELECT ENAME, SAL, DEPTNO, RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) "급여 순위"
FROM EMP

-- PIVOT  예시
SELECT * FROM EMP
PIVOT(MAX(SAL),FOR DEPTNO IN (10,20,300;)




